# Generated by Django 5.2.7 on 2025-10-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='message_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order'),
        ),
    ]
