# Generated by Django 5.2.7 on 2025-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
