
#__________________________Constants for Data Generation_______________________#

LOCATIONS = [
    "Mekele, Tigray",
    "Kobo, Amhara",
    "Meki, Oromia",
    "Jimma, Oromia",
    "Sidama, Sidama",
    "Shashemene, Oromia",
    "Asella, Oromia",
    "Addis Ababa, Addis Ababa",
    "Adama, Oromia",
    "Bahir Dar, Amhara",
    "Hawassa, Sidama",
    "Gondar, Amhara",
    "Dire Dawa, Dire Dawa",
    "Arba Minch, SNNPR",
    "Dessie, Amhara",
    "Harar, Harari"
]

Names = [
"Abeba", "አበበ", "Abel", "አበራሽ", "Abraham", "አዲስ", "Addisu", "አክሊሉ", "Alemayehu", "አልማዝ",
"Amanuel", "አማረ", "Andualem", "አሸናፊ", "Aster", "አያና", "Azeb", "በረከት", "Berhanu", "ቤተልሔም",
"Binyam", "ብሩክ", "Daniel", "ዳዊት", "Desta", "ኤደን", "Eleni", "ኤርሚያስ", "Fana", "ፋሲካ",
"Feven", "ፍቅሬ", "Gebre", "ገነት", "Haile", "ሃና", "Helen", "ሄኖክ", "Kaleab", "ከበደ",
"Kidist", "ቅዱስ", "Lemlem", "ሊሻን", "Martha", "መዓዛ", "Mekdes", "መኮንን", "Mengistu", "መሰረት",
"Michael", "ራሔል", "Saba", "ሳሙኤል", "Selam", "ሰለሞን", "Tadesse", "ታምራት", "Tesfaye", "ትዕግስት",
"Tsehay", "ውበቴ", "Yared", "ዮሐንስ", "Zelalem", "ዙፋን", "Aida", "አፈወርቅ", "Birhan", "ብስራት",
"Dawit", "ድራሮ", "Elias", "እመቤት", "Fasil", "ፍሬወይኒ", "Girma", "ጌታቸው", "Hiwot", "ህይወት",
"Jemal", "ቃልኪዳን", "Lidet", "ልደት", "Makeda", "ማክዳ", "Nahom", "ናሆም", "Rediet", "ርብቃ",
"Samrawit", "ሳምራዊት", "Tilahun", "ጥላሁን", "Yonas", "ዮናስ", "Zenebech", "ዘነበች", "Abigail", "አቢሲኒያ",
"Bruk", "ቤዛ", "Abriham", "አብርሃም", "Adanech", "አዳነች", "Admasu", "አድማሱ", "Afework", "አፈወርቅ",
"Ahadu", "አሀዱ", "Alazar", "አልአዛር", "Alemitu", "አለሚቱ", "Alem", "አለም", "Amha", "አምሃ",
"Anteneh", "አንተነህ", "Arsema", "አርሴማ", "Asrat", "አስራት", "Ayantu", "አያንቱ", "Bekele", "በቀለ",
"Belay", "በላይ", "Beniam", "ቤኒያም", "Bereket", "በረከት", "Betelhem", "ቤተልሔም", "Bezawit", "ቤዛዊት",
"Biftu", "ቢፍቱ", "Bizu", "ብዙ", "Chala", "ጫላ", "Chernet", "ቸርነት", "Debre", "ደብረ",
"Demeke", "ደመቀ", "Dereje", "ደረጀ", "Eden", "ኤደን", "Endale", "እንዳለ", "Eshetu", "እሸቱ",
"Eyob", "ኢዮብ", "Ezana", "ኢዛና", "Fanuel", "ፋኑኤል", "Feker", "ፍቅር", "Fisseha", "ፍስሃ",
"Frehiwot", "ፍሬህይወት", "Gadise", "ገዲሴ", "Getachew", "ጌታቸው", "Getnet", "ጌትነት", "Gideon", "ጊዴዎን",
"Habtamu", "ሀብታሙ", "Hagos", "ሃጎስ", "Haimanot", "ሃይማኖት", "Hasset", "ሀሴት", "Hawani", "ሀዋኒ",
"Heran", "ሄራን", "Iman", "ኢማን", "Israel", "እስራኤል", "Kalkidan", "ቃልኪዳን", "Kassa", "ካሳ",
"Kefyalew", "ክፍያለው", "Keneni", "ቀነኒ", "Kibrom", "ኪብሮም", "Kokeb", "ኮከብ", "Leul", "ልዑል",
"Lidiya", "ሊዲያ", "Liya", "ሊያ", "Mahlet", "ማህሌት", "Mati", "ማቲ", "Melat", "መላት",
"Melesse", "መለሰ", "Meron", "ሜሮን", "Mesfin", "መስፍን", "Meti", "መቲ", "Mignot", "ምኞት",
"Mihret", "ምህረት", "Million", "ሚሊዮን", "Muluken", "ሙሉቀን", "Nardos", "ናርዶስ", "Natan", "ናታን",
"Nebiyat", "ነቢያት", "Netsanet", "ነፃነት", "Raey", "ራእይ", "Robel", "ሮቤል", "Ruth", "ሩት",
"Samri", "ሳምሪ", "Sara", "ሳራ", "Seble", "ሰብለ", "Seifu", "ሰይፉ", "Semira", "ሰሚራ",
"Senait", "ሰናይት", "Shimelis", "ሽመልስ", "Shitaye", "ሽታዬ", "Sifan", "ሲፋን", "Sisay", "ሲሳይ",
"Siyum", "ሲዩም", "Tamerat", "ታምራት", "Tariku", "ታሪኩ", "Tatek", "ታጠቅ", "Tewodros", "ቴዎድሮስ",
"Tigist", "ትዕግስት", "Tinsae", "ትንሳኤ", "Tizita", "ትዝታ", "Tsega", "ፀጋ", "Wondimu", "ወንድሙ",
"Workneh", "ወርቅነህ", "Yabsira", "ያብስራ", "Yakob", "ያዕቆብ", "Yanet", "ያኔት", "Yeabsira", "የአብስራ",
"Yegna", "የኛ", "Yemane", "የማነ", "Yenenesh", "የነነሽ", "Yeshi", "የሺ", "Yidnek", "ይድነቅ",
"Yishak", "ይсሀቅ", "Yitbarek", "ይትባረክ", "Yohana", "ዮሃና", "Zeben", "ዘበን", "Zekarias", "ዘካሪያስ",
"Zemzem", "ዘምዘም", "Zerihun", "ዘሪሁን", "Zufan", "ዙፋን", "Abenezer", "አቤኔዘር", "Adonay", "አዶናይ",
"Aman", "አማን", "Bahlbi", "ባህልቢ", "Bona", "ቦና", "Dagim", "ዳግም", "Eba", "ኤባ",
"Ephrem", "ኤፍሬም", "Eyuel", "እዩኤል", "Firaol", "ፊራኦል", "Fitsum", "ፍጹም", "Habtom", "ሃብቶም",
"Henos", "ሄኖስ", "Kaleb", "ካሌብ", "Luel", "ልዑል", "Merih", "ሜሪህ", "Mulu", "ሙሉ",
"Natnael", "ናትናኤል", "Nigist", "ንግስት", "Rahwa", "ራህዋ", "Redyet", "ረድኤት", "Salome", "ሰሎሜ",
"Surafel", "ሱራፌል", "Tarik", "ታሪክ", "Temesgen", "ተመስገን", "Wengel", "ወንጌል", "Yafet", "ያፌት",
"Yididiya", "ይዲዲያ", "Zufan", "ዙፋን", "Abezu", "አበዙ", "Adel", "አዴል", "Alebel", "አለበል",
"Alem-Tsehay", "አለምፀሀይ", "Amarech", "አማረች", "Amsale", "አምሳለ", "Asnake", "አስናቀ", "Ayele", "አየለ",
"Bahiru", "ባህሩ", "Belainesh", "በላይነሽ", "Berhane", "ብርሃኔ", "Bete", "ቤቴ", "Chuchu", "ጩጩ",
"Dehab", "ደሃብ", "Emebet", "እመቤት", "Enku", "እንቁ", "Etenesh", "እቴነሽ", "Feleke", "ፈለቀ",
"Genet", "ገነት", "Habte", "ሃብቴ", "Hirut", "ሂሩት", "Kassahun", "ካሳሁን", "Kiros", "ኪሮስ",
"Letebirhan", "ለተብርሃን", "Leyla", "ለይላ", "Lishan", "ልሻን", "Mame", "ማሜ", "Mekonnen", "መኮንን",
"Mengesha", "መንገሻ", "Mesay", "መሳይ", "Moges", "ሞገስ", "Nega", "ነጋ", "Nishan", "ኒሻን",
"Sihin", "ስሂን", "Tessema", "ተሰማ", "Tewabech", "ተዋበች", "Tibebu", "ጥበቡ", "Tiru", "ጥሩ",
"Wub", "ውብ", "Yalew", "ያለው", "Yohannes", "ዮሃንስ", "Zewde", "ዘውዴ", "Addisalem", "አዲስአለም",
"Admassu", "አድማሱ", "Akal", "አካል", "Aklile", "አክሊለ", "Alehegn", "አለኸኝ", "Amsal", "አምሳል",
"Aregash", "አረጋሽ", "Assefa", "አሰፋ", "Banchu", "ባንቹ", "Baye", "ባዬ", "Bedelcha", "በደልቻ",
"Behailu", "በኃይሉ", "Belachew", "በላቸው", "Bereded", "በረደድ", "Chalchisa", "ጫልችሳ", "Chaltu", "ጫልቱ",
"Dagnew", "ዳኘው", "Dagmawi", "ዳግማዊ", "Danait", "ዳናይት", "Demis", "ደጀን", "Dibaba", "ዲባባ",
"Dinah", "ዲና", "Dinknesh", "ድንቅነሽ", "Edom", "ኤዶም", "Eleni", "እሌኒ", "Elsa", "ኤልሳ",
"Endalk", "እንዳልክ", "Engida", "እንግዳ", "Eskedar", "እስከዳር", "Estifanos", "እስጢፋኖስ", "Etana", "ኤታና",
"Fekadu", "ፈቃዱ", "Fenet", "ፍነት", "Freweyni", "ፍሬወይኒ", "Gashaw", "ጋሻው", "Gezachew", "ገዛቸው",
"Haben", "ሃበን", "Hadush", "ሃዱሽ", "Hamelmal", "ሃመልማል", "Hanna", "ሃና", "Hawi", "ሃዊ",
"Hirut", "ሂሩት", "Jalane", "ጃላኔ", "Jemal", "ጀማል", "Kahsay", "ካሕሳይ", "Kassa", "ካሳ",
"Kassaye", "ካሳዬ", "Kenea", "ቀነአ", "Kibret", "ክብረት", "Lalla", "ላላ", "Lemma", "ለማ",
"Lewi", "ሌዊ", "Lulit", "ሉሊት", "Mastewal", "ማስተዋል", "Maza", "ማዛ", "Meaza", "መዓዛ",
"Medina", "መዲና", "Meheret", "ምህረት", "Melaku", "መላኩ", "Melkam", "መልካም", "Menbere", "መንበረ",
"Merema", "መረማ", "Meskere", "መስከረ", "Mestawet", "መስታወት", "Mulugeta", "ሙሉጌታ", "Nebil", "ነቢል",
"Nigatu", "ንጋቱ", "Oli", "ኦሊ", "Qalbesa", "ቃልበሳ", "Rahma", "ራህማ", "Ramla", "ራምላ",
"Ruta", "ሩታ", "Saada", "ሳዳ", "Salah", "ሳላህ", "Samson", "ሳምሶን", "Selamawit", "ሰላማዊት",
"Semegn", "ስመኝ", "Shiferaw", "ሽፈራው", "Simret", "ስምረት", "Sirak", "ሲራክ", "Soliana", "ሶሊያና",
"Taddese", "ታደሰ", "Takele", "ታከለ", "Tefera", "ተፈራ", "Tefra", "ተፍራ", "Tekle", "ተክሌ",
"Temima", "ተሚማ", "Terefe", "ተረፈ", "Tesfahun", "ተስፋሁን", "Tigabu", "ጢጋቡ", "Tizazu", "ትዛዙ",
"Tolossa", "ቶሎሳ", "Wagaye", "ዋጋዬ", "Wessen", "ወሰን", "Yacob", "ያቆብ", "Yalem", "ያለም",
"Yemariam", "የማርያም", "Yerosan", "ዬሮሳን", "Yewubdar", "የውብዳር", "Yibeltal", "ይበልጣል", "Yihun", "ይሁን",
"Yordanos", "ዮርዳኖስ", "Zahra", "ዛህራ", "Zakarias", "ዘካሪያስ"
]

Products = [
    "Red Onions", "ቲማቲም", "Potatoes", "ነጭ ሽንኩርት", "Cabbage", "ካሮት",
    "Green Peppers", "ጎመን", "Avocados", "ሙዝ", "Mangoes", "ፓፓያ", "Oranges",
    "ሎሚ", "Watermelon", "ወተት", "Yogurt", "ቅቤ", "Sweet Potatoes", "ዝንጅብል"
]

# The 20 unique products that can be sold on the platform.
PRODUCTS_CATALOG = {
    "Red Onions": "red_onions",
    "ቲማቲም": "tomatoes",
    "Potatoes": "potatoes",
    "ነጭ ሽንኩርት": "garlic",
    "Cabbage": "cabbage",
    "ካሮት": "carrots",
    "Green Peppers": "green_peppers",
    "ጎመን": "collard_greens",
    "Avocados": "avocados",
    "ሙዝ": "bananas",
    "Mangoes": "mangoes",
    "ፓፓያ": "papayas",
    "Oranges": "oranges",
    "ሎሚ": "lemons",
    "Watermelon": "watermelon",
    "ወተት": "milk",
    "Yogurt": "yogurt",
    "ቅቤ": "kibe",
    "Sweet Potatoes": "sweet_potatoes",
    "ዝንጅብል": "ginger"
}

PRODUCT_ENHANCEMENTS = {
    "red_onions":     {"price": 45.0,  "peak_month": 10}, 
    "tomatoes":       {"price": 50.0,  "peak_month": 11}, 
    "potatoes":       {"price": 30.0,  "peak_month": 11}, 
    "garlic":         {"price": 150.0, "peak_month": 9},
    "cabbage":        {"price": 25.0,  "peak_month": 12}, 
    "carrots":        {"price": 35.0,  "peak_month": 12},
    "green_peppers":  {"price": 60.0,  "peak_month": 10},
    "collard_greens": {"price": 20.0,  "peak_month": 9},  
    "avocados":       {"price": 90.0,  "peak_month": 7}, 
    "bananas":        {"price": 50.0,  "peak_month": 5},  
    "mangoes":        {"price": 80.0,  "peak_month": 5},  
    "papayas":        {"price": 70.0,  "peak_month": 6},
    "oranges":        {"price": 65.0,  "peak_month": 1},
    "lemons":         {"price": 75.0,  "peak_month": 1},
    "watermelon":     {"price": 15.0,  "peak_month": 4}, 
    "milk":           {"price": 85.0,  "peak_month": 8},  
    "yogurt":         {"price": 95.0,  "peak_month": 8},
    "kibe":           {"price": 1200.0,"peak_month": 8},
    "sweet_potatoes": {"price": 40.0,  "peak_month": 11},
    "ginger":         {"price": 180.0, "peak_month": 12}
}